import Navbar from '@/components/ui/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '@/components/ui/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'PICTURE GALLERY',
  description: 'Generated by Jawad',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className={inter.className}>
        <Navbar/>
        <div className='flex '>
        <Sidebar/>
        <div className='w-full px-4 pt-12'>
        {children}
        </div>
        </div>
        </body>
    </html>
  )
}
